### ISSUE TITLE
Problem with inicialization MySQL script 

### ISSUE THREAD

**Issue by jm2garrido** [telefonicaid/fiware-rss#18]
Hi, 

I installed the RSS in a Ubuntu 14.04 with MySQL 5.5.44. When I executed 

mysql -uroot -proot FIWARE_SETTLEMENT < ./rss-core/resources/datamodel/dbmodel.sql

The system returns a cryptic error:

ERROR 1064 (42000) at line 507: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3

At the end, the problem is that we need to put DELIMITER $$ before defining the stored procedure. This is the correct text (at least, for me)

```
#
# Procedure "refunded_yn"
#
DROP PROCEDURE IF EXISTS `refunded_yn`;
DELIMITER $$
CREATE PROCEDURE `refunded_yn`()
BEGIN
    DECLARE v_finished INTEGER DEFAULT 0;
    DECLARE id VARCHAR(40);
    -- declare cursor for tx_transaction_id
    DECLARE cur1 CURSOR FOR SELECT tx_org_transaction_id FROM dbe_transaction WHERE tc_transaction_type='R';
    -- declare NOT FOUND handler
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET v_finished = 1;

    OPEN cur1;
    update_refunded: LOOP
        FETCH cur1 INTO id;
        IF v_finished = 1 THEN 
            LEAVE update_refunded;
        END IF;
        UPDATE dbe_transaction SET tc_is_refunded_yn='Y' WHERE tc_transaction_type='C' AND tx_transaction_id = id;
    END LOOP update_refunded;
    CLOSE cur1;
END;
$$
```

**Comment by fdelavega** [comment]
Hi,

This repository is not longer maintained. Currenly the RSS is being evolved in:
https://github.com/conwetlab/fiware-rss

Regarding your problem, this does not apply anymore since in the last version of the software tables are automatically created by Hibernate.

Best Regards,
Francisco

**Comment by jm2garrido** [comment]
Thanks Francisco, I'll try it.

Please update the info in the fiware catalog, it is pointing still to this old repository (http://catalogue.fiware.org/enablers/revenue-settlement-and-sharing-system-rss-ri/downloads)
